version: "3.9"  # optional since v1.27.0

x-coord: &coordinator
  image: citus_pg15_autofailover:0.1
  environment:
    PGDATA: /var/lib/postgres/pgaf
    PGUSER: citus
    PGDATABASE: citus
    PG_AUTOCTL_HBA_LAN: true
    PG_AUTOCTL_AUTH_METHOD: "trust"
    PG_AUTOCTL_SSL_SELF_SIGNED: true
    PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
  expose:
    - 5432

x-worker: &worker
  image: citus_pg15_autofailover:0.1
  environment:
    PGDATA: /var/lib/postgres/pgaf
    PGUSER: citus
    PGDATABASE: citus
    PG_AUTOCTL_HBA_LAN: true
    PG_AUTOCTL_AUTH_METHOD: "trust"
    PG_AUTOCTL_SSL_SELF_SIGNED: true
    PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
  expose:
    - 5432

services:
  monitor:
    image: citus_pg15_autofailover:0.1
    environment:
      PGDATA: /var/lib/postgres/pgaf
      PG_AUTOCTL_SSL_SELF_SIGNED: true
    expose:
      - 5432
    command: |
      pg_autoctl create monitor --hostname monitor --auth trust --run
    volumes:
      - monitor-db:/var/lib/postgres

  coord0a:
    <<: *coordinator
    hostname: coord0a
    command: |
      pg_autoctl create coordinator --name coord0a --run
    volumes:
      - coord0a-db:/var/lib/postgres

  coord0b:
    <<: *coordinator
    hostname: coord0b
    command: |
      pg_autoctl create coordinator --name coord0b --run
    volumes:
      - coord0b-db:/var/lib/postgres

  worker1a:
    <<: *worker
    hostname: worker1a
    command: |
      pg_autoctl create worker --group 1 --name worker1a --run

    volumes:
      - worker1a-db:/var/lib/postgres

  worker1b:
    <<: *worker
    hostname: worker1b
    command: |
      pg_autoctl create worker --group 1 --name worker1b --run
    volumes:
      - worker1b-db:/var/lib/postgres

  worker2a:
    <<: *worker
    hostname: worker2a
    command: |
      pg_autoctl create worker --group 2 --name worker2a --run
    volumes:
      - worker2a-db:/var/lib/postgres

  worker2b:
    <<: *worker
    hostname: worker2b
    command: |
      pg_autoctl create worker --group 2 --name worker2b --run
    volumes:
      - worker2b-db:/var/lib/postgres

  worker3a:
    <<: *worker
    hostname: worker3a
    command: |
      pg_autoctl create worker --group 3 --name worker3a --run
    volumes:
      - worker3a-db:/var/lib/postgres

  worker3b:
    <<: *worker
    hostname: worker3b
    command: |
      pg_autoctl create worker --group 3 --name worker3b --run
    volumes:
      - worker3b-db:/var/lib/postgres

volumes:
  monitor-db:
  coord0a-db:
  coord0b-db:
  worker1a-db:
  worker1b-db:
  worker2a-db:
  worker2b-db:
  worker3a-db:
  worker3b-db:
  
